export default {
  /* Not ready yet 

  AREAS_BLOG: {
    title: "Areas Blog",
    dataPacks: ["BLOG"],
    local: true,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  INSIGHT_AREAS: {
    title: "Insight Areas",
    dataPacks: ["INSIGHTS"],
    local: true,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  AUTHOR: {
    title: "Author",
    dataPacks: ["PUBLICATIONS", "INSIGHTS"],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  SUBJECT: {
    title: "Subject",
    dataPacks: ["INSIGHTS"],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  FORMAT: {
    title: "Format",
    dataPacks: ["EVENTS", "INSIGHTS"],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },


  AWARDS: {
    title: "Awards",
    dataPacks: ["EPIC_AWARDS"],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  RANKING_AUTHOR: {
    title: "Ranking Author",
    dataPacks: ["RANKINGS"],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  SCHOOLS: {
    title: "Schools",
    dataPacks: ["NEWS", "INSIGHTS", "TESTIMONIALS"],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  PROFILE: {
    title: "Profile",
    dataPacks: ["PROJECTS", "STORIES"],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  */

  // PROGRAMS: {
  //   title: "Programs",
  //   dataPacks: ["PROJECTS"],
  //   local: false,
  //   taxonomy: true,
  //   fromPage: false,
  //   translate: true,
  //   schema: null,
  //   clone: null,
  //   defaults: null,
  // },

  NEWS_AREAS: {
    title: 'News Areas',
    dataPacks: ['NEWS'],
    local: true,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  PUBLICATIONS_AREAS: {
    title: 'Publications Areas',
    dataPacks: ['PUBLICATIONS'],
    local: true,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  EVENT_AREAS: {
    title: 'Event Areas',
    dataPacks: ['EVENTS'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  LOCATION: {
    title: 'Location',
    dataPacks: ['EVENTS'],
    local: true,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  EVENT_FORMATS: {
    title: 'Event Formats',
    dataPacks: ['EVENTS'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  EVENT_LOCATIONS: {
    title: 'Event Locations',
    dataPacks: ['EVENTS'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  EVENT_REGION: {
    title: 'Event Region',
    dataPacks: ['EVENTS'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  //YEAR: {
  //title: "Type",
  //dataPacks: ["RANKINGS", "EPIC_AWARDS"],
  //local: false,
  //taxonomy: true,
  //fromPage: false,
  //translate: true,
  //schema: null,
  //clone: null,
  //defaults: null,
  //},

  //TYPE: {
  //title: "Type",
  //dataPacks: ["STORIES", "EPIC_AWARDS"],
  //local: false,
  //taxonomy: true,
  //fromPage: false,
  //translate: true,
  //schema: null,
  //clone: null,
  //defaults: null,
  //},

  PROGRAM_TYPES: {
    title: 'Program Types',
    dataPacks: ['EVENTS', 'STORIES'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  STORY_TYPE: {
    title: 'Story Type',
    dataPacks: ['STORIES'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  STORY_PROFILE: {
    title: 'Story Profile',
    dataPacks: ['STORIES'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  TEACHER_CATEGORY: {
    title: 'Teacher Category',
    dataPacks: ['TEACHERS'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  TEACHER_TYPE: {
    title: 'Teacher Type',
    dataPacks: ['TEACHERS'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  TEACHER_AREAS: {
    title: 'Teacher Areas',
    dataPacks: ['TEACHERS'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },

  GLOBAL_NEWS: {
    title: 'Global News',
    dataPacks: ['NEWS'],
    local: false,
    taxonomy: true,
    fromPage: false,
    translate: true,
    schema: null,
    clone: null,
    defaults: null,
  },
}
